version: '3'
services:
  
  postgres:
    container_name: postgresdb
    image: postgres:latest
    build: \POSTGRES\.
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
  
  
  pythonapp:
    image: project:latest
    build: \APP\.
    depends_on:
      - postgres
    ports:
      - 8000:8000
  
 
  fronted:
    image: fronted:latest
    build: .\APP\templates\
    ports:
      - 8080:8080
  




