version: '3'
services:
  
  postgres:
    container_name: postgresdb
    image: postgres:latest
    build: \POSTGRES\.
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
  
  
  pythonapp:
    container_name: backend
    image: project:latest
    build: \APP\.
    depends_on:
      - postgres
    ports:
      - 8000:8000
  
 
  frontend:
    container_name: frontend
    image: frontend:latest
    build: ./APP/templates/
    ports:
      - 8501:8501
  




